Id: 019bdf12-0d1a-78d6-b77d-cfdea716863f
CompatibilityMode: 8.0
Vendor: admin
Name: test1
Version: 1.0
Presentation: "Test 1"
VendorPresentation: "admin"
LocalizationLanguages: [Russian]
DefaultLanguage: Russian
DevelopmentLanguage: English
